language: node_js
node_js:
  - 16

services:
  - docker

before_install: #pre-deployment
  - docker build -t william922/reactappprac -f Dockerfile.dev .

script: #build
  -docker run william922/reactappprac npm run test -- --coverage